### PR TITLE
Fix empty artifacts.

### PR DESCRIPTION
**Pull request by phracek**
The print empty field in the case of artifacts are not defined.

Also other small fixes.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
@fernflower Can you please review it? It should be simple

**Review by fernflower — COMMENTED** [review]
Sorry, I don't have time to try this out right now but given the number of small fixes I had to do in https://github.com/sclorg/testing-farm-as-github-action/pull/24 you'd better make a real test run before the merge. I shared the way I test changes to workflows https://github.com/sclorg/testing-farm-as-github-action/issues/30#issuecomment-1041341230, maybe you could do the same?
I am afraid I won't get to real testing till next week, something else came up. 

Otherwise looks logical, but with workflows you never know until you run it for real.
Also please add 'Closes: #30' to the commit message.

**Comment by phracek** [comment]
I have tested this update by https://github.com/phracek/testing-farm-as-github-action/blob/main/action.yml  on  https://github.com/phracek/nginx-container/pull/2.
It looks everything is working well.

**Review by fernflower — APPROVED** [review]
lgtm! Thanks!

**Pull request merged**
