### PR TITLE
fix: job summary link :link: 

### PR DESCRIPTION
**Pull request by jamacku**

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
Thanks for the PR, it works. However, I think we should provide the Test Logs, not pipeline log, when infra state is OK. But this is not a strong opinion.
image

**Comment by jamacku** [comment]
Like this?

<table><tr><th>Compose</th><th>Arch</th><th>Infrastructure State</th><th>Test result</th><th>Link to logs</th></tr><tr><td>Fedora-latest</td><td>x86_64</td><td>OK</td><td>success</td><td><a href="https://artifacts.dev.testing-farm.io/1">test</a> <a href="https://artifacts.dev.testing-farm.io/1/pipeline.log">pipeline</a></td></tr></table>

**Comment by zmiklank** [comment]
> Like this?

Yes, seems nice. :)

**Comment by zmiklank** [comment]
[test]

**Review by zmiklank — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
