### PR TITLE
provide better access to test logs

### PR DESCRIPTION
**Pull request by zmiklank**
Related:  https://github.com/sclorg/testing-farm-as-github-action/issues/130

@jamacku PTAL.

### CODE REVIEW

**Comment by thrix** [comment]
did this break recently?

https://redhat-internal.slack.com/archives/C03BRN71JAF/p1709834829608519?thread_ts=1709824147.944019&cid=C03BRN71JAF

**Comment by zmiklank** [comment]
Hi @thrix. Yes, it seems we stopped showing the tests log URL in our logs in v2.

**Comment by phracek** [comment]
AS far as I know, it was present in Bash version. See here: https://github.com/sclorg/testing-farm-as-github-action/blob/3e8634e3591903f8aeeb192af57e80801d4a85d4/action.yml#L91

**Review by phracek — APPROVED** [review]
LGTM. I looked at code and did not hit any issue.

**Review by jamacku — CHANGES_REQUESTED** [review]
@zmiklank, please also add tests for the new output so we do not cause regressions later.

For reference:

https://github.com/sclorg/testing-farm-as-github-action/blob/6d060a156906635697acd8e980c25e6d431c2e9b/tests/action.test.ts#L220-L224

**Comment by zmiklank** [comment]
> @zmiklank, please also add tests for the new output so we do not cause regressions later.

Good catch, thanks. Added.

**Review by jamacku — APPROVED** [review]
LGTM

**Pull request merged**
