### PR TITLE
Add support for issue metadata and dynamic summary

### PR DESCRIPTION
**Pull request by jamacku**
It replaces the old comment logic with the new one that uses issue metadata
to story helper data. It allows us to create only one comment with a summary
of all tests and their results, which is dynamically updated.

Also, enable issue comments for our Testing Farm GitHub Action repository.

---

Replaces:
- #211 

TODO:

- [ ] Show some pictures
- [ ] Handle cancel events

### CODE REVIEW

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Review by phracek — CHANGES_REQUESTED** [review]
I don't know now if this change is braking, but I have one proposal. I guess 'pull_request_status_name' needs to be dependent on Summary.
What about if 'pull_request_status_name' is not defined?

**Review by phracek — COMMENTED** [review]
But this is amazing work. Thanks for moving TFaGA to be more effective and usable for users.

**Comment by jamacku** [comment]
> I don't know now if this change is braking, but I have one proposal. 

I set it as breaking because we are changing the content and behavior of the comment. Previously, we created a new comment for each run of the Action (a new notification was sent). Now, we create only one comment, which we update, so only one notification is sent.

> I guess 'pull_request_status_name' needs to be dependent on Summary. What about if 'pull_request_status_name' is not defined?

`pull_request_status_name` has a default value of `Fedora`. But I think everyone is using statuses and changing/setting the `pull_request_status_name` input to some value.

**Review by phracek — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
