### PR TITLE
Generate tmt_context by generate_tmt_vars.py

### PR DESCRIPTION
**Pull request by phracek**
This pull request generates tmt_context by generate_tmt_vars.py
This is only pre-migration step.

Every variable will be generated by python scripts introduced by PR https://github.com/sclorg/testing-farm-as-github-action/pull/48
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
The tests look great! :)

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
This is not valid anymore. We will use TypeScripc soon.

**Pull request closed without merging**
