### PR TITLE
Introduce environment_settings input

### PR DESCRIPTION
**Pull request by fernflower**
This will allow passing custom environment settings to the test env,
like specific post-install-scripts to be run during guest provisioning.

OAMG-6748

### CODE REVIEW

**Comment by fernflower** [comment]
Proof that it works - https://api.dev.testing-farm.io/v0.1/requests/a6f06f58-9c78-4e34-9126-589ccc455703 
(https://github.com/fernflower/leapp-repository/pull/6 and action https://github.com/fernflower/leapp-repository/actions/runs/2238477947)

**Comment by fernflower** [comment]
@phracek @zmiklank @thrix Please review

**Comment by phracek** [comment]
@fernflower The pull request itself is fine. But based on the API definition https://testing-farm.gitlab.io/api/#operation/requestsPost
there is not any 'provisioning' like https://github.com/fernflower/leapp-repository/blob/master/.github/workflows/tmt-tests.yml#L169 only 'worker'? Is this intended? Or API is not updated @thrix ?

**Comment by fernflower** [comment]
@phracek Well it's bleeding edge, but it's already there https://testing-farm.gitlab.io/api/#operation/requestsPost (the environment.settings.provisioning.post_install_script)

**Review by phracek — APPROVED** [review]
LGTM

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
