### PR TITLE
feat: allow to provide context for non-PR events

### PR DESCRIPTION
**Pull request by jamacku**
Adding new inputs:

- `repo_owner` Owner of the repository
- `repo_name` Name of the repository
- `pr_number` Pull request number for showing the results
- `commit_sha` Sha of the commit triggering the action

### CODE REVIEW

**Comment by jamacku** [comment]
@yih-redhat, Could you please test this PR? 

```yml
uses: jamacku/testing-farm-as-github-action@support-nonpr-context
with:
  #  ...
```

You can use new inputs: `repo_owner`, `repo_name`, `pr_number` and `commit_sha` to provide additional information when running on repository_dispatch. The `commit_sha` is optional when running on repository_dispatch trigger.

**Comment by yih-redhat** [comment]
Sure, I will test it and let you know the result.

**Comment by yih-redhat** [comment]
@jamacku I have tested this pr, it works as expected.
PR https://github.com/osbuild/osbuild-composer/pull/4240 triggered ci test https://github.com/osbuild/rhel-edge-ci/actions/runs/10268536294, when test started, I can see a new test status created in that PR, and after test finished, the test result is also updated in that PR, perfect!

**Comment by yih-redhat** [comment]
Yes, it works well at my first try with a small test case. Now I have started a full test with this pr with 10 test cases, and will let you know if anything wrong.
You can also check the result at https://github.com/osbuild/osbuild-composer/pull/4240 (It's building now, testing-farm test will not be triggered until build finished), tfaga is configured at https://github.com/osbuild/rhel-edge-ci/blob/main/.github/workflows/rhel-95.yml

**Review by phracek — APPROVED** [review]
LGTM. Thanks. Do not block this issue for the other. Let's wait for real results.

**Comment by jamacku** [comment]
test

**Comment by phracek** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Comment by jamacku** [comment]
[test]

**Pull request merged**
